server:
  port: 6974

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbinc?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    http:
      media-types:
        hwp: application/vnd.hancom.hwp

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL 보기 좋게 출력
        "[user_sql_comments]": true     #SQL 생성시 주석 포함
        "[highlight_sql]": true         #SQL 색깔
        "[hbm2ddl.auto]": update
    open-in-view: true
    show-sql: true

servlet:
  multipart:
    max-file-size: 10000MB
    max-request-size: 10000MB

jwt:
  header: "Authorization"
  prefix: "Bearer"
  secret: uvESMHdRLR7Pfv//eYSTNbsCkoJRmRmU8OcbdUKwWO8faLh1FkYCL55cl5J+4zzOfrB+ZsSqOBX5nzrf3EmRxg==
  tokenExpirationTime: 180000

project:
  folderPath: "files/"